version: '3.4'

services:
  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "security"

  mailserver:
    image: reachfive/fake-smtp-server
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"