version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/security
      - SECURITY_JASPY_SECRET=${SECURITY_JASPY_SECRET}
      - SECURITY_JASPY_SALT=${SECURITY_JASPY_SALT}
      - SECURITY_JASPY_ALGORITHM=${SECURITY_JASPY_ALGORITHM}

  postgres:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "security"