spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://${database.host}:${database.port}/${database.name}"
    username: "${database.username}"
    password: "${database.password}"
    driver-class-name: "org.postgresql.Driver"
    flyway:
      enabled: true

database:
  host: "localhost"
  port: 5432
  username: "root"
  password: "password"
  name: "security"

server:
  port: 8080

jwt:
  access:
    secret: ENC(7NxeuF4Fua9h49fFp9AqonOrK53xcD3dy9cUzqV2JbPpffkqgvM0HIC7hq6O1kuG76MMfx2O+rlEkD5lXjBD8RwGF8PGGl8teTfZQynpiEvLiSZLM1pompD5k5AN9WbAMGWmEH/J+e9W+2XKLeSQ1+FsACedx4oYZ595jh7E9lx4JJn3v4REMW7fSMkMKcb3vIwJpswyxB53RvHc)
    expirationDays: 60
  refresh:
    secret: ENC(e8K6OLLC1J1SpUOcTQ/HngH0m5BlQkYmqs5MMeyGA6tVdhz2NccIYS33JOfKMy3/6vzi/M7fzeXHGI9HlwrCesU7XRmrodz6dMEDzy339BXfiBPyYFA6XdQMTUNJYFX385VVeFyGGVkUAdQTnSDJAW5vCkNcarQBemqRzni5VaTuPQX6MIoJWK4JFWLwscUedGcpP4hPpWVPwyNs)
    expirationDays: 365
  issuer: ENC(j7dv2PyCrwN+Lq1S5W0wI+KrclF2v+ximRXx3q8+ZwfsNg==)

verification:
  email:
    auth-enabled: false
    from: ENC(5kEgP/YxYkGZHrAXoSUrK+09GcOtQiyueFDE1ZIpqOZPKSJkKAo0BDlJCgbc)
    password: ENC(CLO9n2y8Z0BPW4Rs9h+DHqfpGrEiiZtINU89F6RenWaxSmoSykYRHvqW3kg=)
    host: "mailserver"
    port: 1025
  valid-minutes: 15

jasypt:
  encryptor:
    gcm-secret-key-password: ${SECURITY_JASPY_SECRET}
    gcm-secret-key-salt: ${SECURITY_JASPY_SALT}
    gcm-secret-key-algorithm: ${SECURITY_JASPY_ALGORITHM}