CREATE TABLE VERIFY
(
    USER_ID         UUID,
    VERIFICATION    VARCHAR(256) NOT NULL,
    CREATION_DATE   TIMESTAMP    NOT NULL,
    EXPIRATION_DATE TIMESTAMP    NOT NULL,
    VALIDATED       BOOLEAN      NOT NULL,
    USABLE          BOOLEAN      NOT NULL,
    TYPE            VARCHAR(128) NOT NULL,
    PRIMARY KEY (USER_ID, CREATION_DATE),
    FOREIGN KEY (USER_ID) REFERENCES SECURITY_USER (ID)
);
