CREATE TABLE VERIFY
(
    USER_ID         UUID,
    VERIFICATION    VARCHAR(255) NOT NULL,
    CREATION_DATE   TIMESTAMP    NOT NULL,
    EXPIRATION_DATE TIMESTAMP    NOT NULL,
    USED            BOOLEAN      NOT NULL,
    PRIMARY KEY (USER_ID, CREATION_DATE),
    FOREIGN KEY (USER_ID) REFERENCES SECURITY_USER (ID)
);
